-- Reward claims are issued by trusted server endpoints and consumed through this RPC.
-- Public clients must not insert, read, or patch reward_claims directly.

CREATE TABLE IF NOT EXISTS public.reward_claims (
  code TEXT,
  reward_id TEXT,
  source TEXT,
  created_at TIMESTAMPTZ,
  claimed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ
);

ALTER TABLE public.reward_claims
  ADD COLUMN IF NOT EXISTS code TEXT,
  ADD COLUMN IF NOT EXISTS reward_id TEXT,
  ADD COLUMN IF NOT EXISTS source TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

UPDATE public.reward_claims
SET created_at = now()
WHERE created_at IS NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.reward_claims
    WHERE code IS NULL OR char_length(btrim(code)) < 16
  ) THEN
    RAISE EXCEPTION 'reward_claims.code must be non-null and at least 16 trimmed characters before enabling public RPC consumption';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.reward_claims
    WHERE reward_id IS NULL OR char_length(btrim(reward_id)) = 0
  ) THEN
    RAISE EXCEPTION 'reward_claims.reward_id must be non-null and non-blank before enabling public RPC consumption';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.reward_claims
    GROUP BY code
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'reward_claims.code contains duplicates; resolve before enabling public RPC consumption';
  END IF;
END;
$$;

ALTER TABLE public.reward_claims
  ALTER COLUMN code SET NOT NULL,
  ALTER COLUMN reward_id SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN created_at SET NOT NULL;

DO $$
DECLARE
  v_pk_columns TEXT[];
BEGIN
  SELECT array_agg(a.attname ORDER BY k.ordinality)
  INTO v_pk_columns
  FROM pg_constraint c
  JOIN unnest(c.conkey) WITH ORDINALITY AS k(attnum, ordinality) ON true
  JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
  WHERE c.conrelid = 'public.reward_claims'::regclass
    AND c.contype = 'p';

  IF v_pk_columns IS NULL THEN
    ALTER TABLE public.reward_claims
      ADD CONSTRAINT reward_claims_pkey PRIMARY KEY (code);
  ELSIF v_pk_columns <> ARRAY['code']::TEXT[] THEN
    RAISE EXCEPTION 'reward_claims primary key must be code, found %', v_pk_columns;
  END IF;
END;
$$;

ALTER TABLE public.reward_claims
  DROP CONSTRAINT IF EXISTS reward_claims_code_entropy_check,
  DROP CONSTRAINT IF EXISTS reward_claims_reward_id_nonblank_check,
  ADD CONSTRAINT reward_claims_code_entropy_check
    CHECK (char_length(btrim(code)) >= 16),
  ADD CONSTRAINT reward_claims_reward_id_nonblank_check
    CHECK (char_length(btrim(reward_id)) > 0);

ALTER TABLE public.reward_claims ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow insert reward claims" ON public.reward_claims;
DROP POLICY IF EXISTS "Allow read reward claims by code" ON public.reward_claims;
DROP POLICY IF EXISTS "Allow update reward claims" ON public.reward_claims;
DROP POLICY IF EXISTS reward_claims_public_insert ON public.reward_claims;
DROP POLICY IF EXISTS reward_claims_public_select ON public.reward_claims;
DROP POLICY IF EXISTS reward_claims_public_update ON public.reward_claims;

REVOKE ALL ON TABLE public.reward_claims FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS public.reward_claim_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reward_id TEXT,
  ok BOOLEAN NOT NULL,
  auth_user_id UUID DEFAULT auth.uid()
);

ALTER TABLE public.reward_claim_attempts
  ADD COLUMN IF NOT EXISTS id BIGINT,
  ADD COLUMN IF NOT EXISTS attempted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reward_id TEXT,
  ADD COLUMN IF NOT EXISTS ok BOOLEAN,
  ADD COLUMN IF NOT EXISTS auth_user_id UUID;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_attribute a
    WHERE a.attrelid = 'public.reward_claim_attempts'::regclass
      AND a.attname = 'id'
      AND a.attidentity <> ''
  )
  AND NOT EXISTS (
    SELECT 1
    FROM pg_attrdef d
    JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
    WHERE d.adrelid = 'public.reward_claim_attempts'::regclass
      AND a.attname = 'id'
  ) THEN
    ALTER TABLE public.reward_claim_attempts
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.reward_claim_attempts
    WHERE id IS NULL OR attempted_at IS NULL OR ok IS NULL
  ) THEN
    RAISE EXCEPTION 'reward_claim_attempts requires non-null id, attempted_at, and ok values';
  END IF;
END;
$$;

ALTER TABLE public.reward_claim_attempts
  ALTER COLUMN id SET NOT NULL,
  ALTER COLUMN attempted_at SET DEFAULT now(),
  ALTER COLUMN attempted_at SET NOT NULL,
  ALTER COLUMN ok SET NOT NULL,
  ALTER COLUMN auth_user_id SET DEFAULT auth.uid();

DO $$
DECLARE
  v_pk_columns TEXT[];
BEGIN
  SELECT array_agg(a.attname ORDER BY k.ordinality)
  INTO v_pk_columns
  FROM pg_constraint c
  JOIN unnest(c.conkey) WITH ORDINALITY AS k(attnum, ordinality) ON true
  JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
  WHERE c.conrelid = 'public.reward_claim_attempts'::regclass
    AND c.contype = 'p';

  IF v_pk_columns IS NULL THEN
    ALTER TABLE public.reward_claim_attempts
      ADD CONSTRAINT reward_claim_attempts_pkey PRIMARY KEY (id);
  ELSIF v_pk_columns <> ARRAY['id']::TEXT[] THEN
    RAISE EXCEPTION 'reward_claim_attempts primary key must be id, found %', v_pk_columns;
  END IF;
END;
$$;

ALTER TABLE public.reward_claim_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.reward_claim_attempts FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.consume_reward_claim(
  p_code TEXT,
  p_reward_id TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
  v_code TEXT := btrim(coalesce(p_code, ''));
  v_requested_reward_id TEXT := btrim(coalesce(p_reward_id, ''));
  v_reward_id TEXT;
BEGIN
  IF char_length(v_code) < 16 OR char_length(v_requested_reward_id) = 0 THEN
    INSERT INTO public.reward_claim_attempts (reward_id, ok, auth_user_id)
    VALUES (nullif(v_requested_reward_id, ''), false, auth.uid());

    RETURN jsonb_build_object('ok', false, 'error', 'invalid_or_used');
  END IF;

  UPDATE public.reward_claims
  SET claimed_at = now()
  WHERE code = v_code
    AND reward_id = v_requested_reward_id
    AND claimed_at IS NULL
    AND (expires_at IS NULL OR expires_at > now())
  RETURNING reward_id INTO v_reward_id;

  INSERT INTO public.reward_claim_attempts (reward_id, ok, auth_user_id)
  VALUES (nullif(v_requested_reward_id, ''), v_reward_id IS NOT NULL, auth.uid());

  IF v_reward_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_or_used');
  END IF;

  RETURN jsonb_build_object('ok', true, 'reward_id', v_reward_id);
END;
$$;

REVOKE ALL ON FUNCTION public.consume_reward_claim(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.consume_reward_claim(TEXT, TEXT) TO anon, authenticated;
